### ISSUE TITLE
Create a switch to allow / disallow grid feeding?

### ISSUE THREAD

**Issue by monstromatic** [ankohanse/hass-studer-xcom#12]
Is it possible to create a switch with param 1127 of XT1 to allow and disallow grid feeding (injection)?
I correctly import the expert param in the configuration, but when I click my switch in HA, nothing happens...

**Comment by ankohanse** [comment]
Hi, functionality for a switch should be there, but I haven't done much testing with it yet. 
So you might very well have runinto a bug...

Any messages visible in the Log (Settings -> System -> Logs and then press 'show full logs') when you click on the switch?

**Comment by monstromatic** [comment]
Hi, thank you for your prompt reply!
No error message about the switch in the HA logs.
The action probably needs to be customised for it to work, like sending 0 or 1. I don't know exactly what the default toggle action produces in this case...

**Comment by ankohanse** [comment]
Don't see anything wrong in the integration code for a Switch entity.

Cannot test with Xtender param 1127 myself as I am not connected to the grid. So tested with 1521 (one of the Aux2 params) instead. Datapoint definitions of those two params are identical (apart from parent number and name), so behavior in code will also be identical:
```
    {   "fam": "xt",   "lvl": "Expert",  "pnr": 1522,   "nr": 1127,   "name": "  Grid feeding allowed",   "unit": "",   "def": 0,   "min": 0,   "max": 1,   "fmt": "BOOL",   "inc": 1 },
    {   "fam": "xt",   "lvl": "Expert",  "pnr": 1456,   "nr": 1521,   "name": "    No overtemperature (AUX 2)",   "unit": "",   "def": 0,   "min": 0,   "max": 1,   "fmt": "BOOL",   "inc": 1 },
```

When switching 1521 on and off I can clearly hear the relay for Aux2 clicking on and off and the connected hot water heater also switches on and off.

From the logs:
```
2024-12-03 10:58:36.103 INFO (MainThread) [custom_components.studer_xcom.switch] Set switch.studer_4001_xt1_1521 to ON (1)
2024-12-03 10:58:36.145 INFO (MainThread) [custom_components.studer_xcom.coordinator] Successfully updated XT1 1521 to value 1
2024-12-03 10:58:41.157 INFO (MainThread) [custom_components.studer_xcom.switch] Set switch.studer_4001_xt1_1521 to OFF (0)
2024-12-03 10:58:41.200 INFO (MainThread) [custom_components.studer_xcom.coordinator] Successfully updated XT1 1521 to value 0
```
So am not able to reproduce the problem :-(

**Comment by ankohanse** [comment]
Can you elaborate with what you mean by 'when I click my switch in HA, nothing happens...'

**Comment by monstromatic** [comment]
I am sorry, I don't know how to set this action correctly on the switch I created...
<img width="1029" alt="Capture d’écran 2024-12-04 à 12 22 36" src="https://github.com/user-attachments/assets/2aa9ada0-29f9-42de-bef8-de66518178cc">

**Comment by monstromatic** [comment]
Should I create a script and attach it to the button?

**Comment by ankohanse** [comment]
The yaml code should look like:
```
    action: switch.turn_on
    target:
      entity_id: switch.studer_4001_xt1_1521
```
or
```
    action: switch.turn_off
    target:
      entity_id: switch.studer_4001_xt1_1521
```
or
```
    action: switch.toggle
    target:
      entity_id: switch.studer_4001_xt1_1521
```

**Comment by monstromatic** [comment]
Here is my switches.yaml code, no error but nothing happens on my XTM : 

    - platform: template
      switches:
        studer_injection:
          value_template: "{{ is_state('switch.studer_4001_xt1_1127', 'on') }}"
          turn_on:
            action: switch.turn_on
            target:
              entity_id: switch.studer_4001_xt1_1127
          turn_off:
            action: switch.turn_off
            target:
              entity_id: switch.studer_4001_xt1_1127
        studer_aux2:
          value_template: "{{ is_state('switch.studer_4001_xt1_1521', 'on') }}"
          turn_on:
            action: switch.turn_on
            target:
              entity_id: switch.studer_4001_xt1_1521
          turn_off:
            action: switch.turn_off
            target:
              entity_id: switch.studer_4001_xt1_1521

**Comment by ankohanse** [comment]
Just a check to be sure, I assume your configuration.yaml contains a line
```
switch: !include switches.yaml
```

And you may need to restart Home Assistant after adding that line to configuraton.yaml

**Comment by ankohanse** [comment]
Also note that instead of making a new/copy template definition for the switches, you can also just rename the original switches in the integration. Choosing a new name, icon or entity_id is allowed, it will not affect updates as internally an object_id is used that will always remain the same value.

So rename from switch.studer_4001_xt1_1127 into switch.studer_injection 
and from switch.studer_4001_xt1_1521 into switch.studer_aux2

![image](https://github.com/user-attachments/assets/fd3058e4-03e6-421c-bf07-6eabe9f4afdc)

**Comment by monstromatic** [comment]
Thank you for your comments.
- I do include switches.yaml in configuration.yaml
- I tried to create a template because initially I was using the switch integration directly without success
- I reload the configuration after each modification

**Comment by monstromatic** [comment]
<img width="1053" alt="Capture d’écran 2024-12-07 à 09 15 23" src="https://github.com/user-attachments/assets/5f1b67bd-8596-4187-b41e-84231f72245c">

**Comment by ankohanse** [comment]
To further analyse this issue, could you please perform the following steps:

- Go to HA Settings->Integrations->Studer-Innotec->Devices->Studer XT1 and click two times on the switch for 1127
- Then go back to the Studer-Innotec integration screen, press the '...' and choose 'download diagnostics'
- Attach the resulting file to your answer below.

![image](https://github.com/user-attachments/assets/a6934508-2fbf-4c09-b91f-e3ddc6f29743)

The diagnostics file contains a section that logs success and fail of request and update commands send to the Studer devices. I would expect it to contain a fail count for your system and hope the 'errors' structure will indicate why:
```
            "UpdateValue XT1 EXPERT": {
              "counters": {
                "success": 2,
                "fail_write": 0,
                "fail_read": 0,
                "fail_timout": 0,
                "fail_error": 0,
                "fail_unpack": 0,
                "fail_other": 0
              },
              "errors": {}
            }
```

**Comment by monstromatic** [comment]
Thanks a lot for the help, I really appreciate it.
Here the section of the diagnostic (but there are no errors):  

    "UpdateValue XT1 EXPERT": {
              "counters": {
                "success": 2,
                "fail_write": 0,
                "fail_read": 0,
                "fail_timout": 0,
                "fail_error": 0,
                "fail_unpack": 0,
                "fail_other": 0
              },
              "errors": {}

I suspect an authorisation problem on the Moxa side...

**Comment by ankohanse** [comment]
No, I don't think it is an authorisation problem. The "success": 2 indicates that the Studer Xcom device confirmed that it has sucessfully updated value. Otherwise the fail_error would have increased. Or one of the other fail_ values if the Xcom device could not be reached.

Are you absolutely sure that no other setting is blocking what you think should happen?
What behavior do you expect to see?

**Comment by ankohanse** [comment]
In addition to the previous comments above, could you please check that your user level is set to at least 'Expert' since you try to change a param of Expert level:

- Go to your RCC screen, 
- Press the down button until you reach 'RCC params', then press 'set'
- Press the down button until you reach 5012 'User Level'.
- Check the value for that param in the bottom right of that screen. 

Alternatively, you can do the same via the online Studer portal (https://portal.studer-innotec.com/) in the 'Remote Control' page
- In the right top of that page it states the 'current user level'.
- Or, in the right bottom, request the value for Parameter Id 5012
- Or in the remote connected screen follow the steps as described above on a physical RCC

Alternatively, update to the latest version of the integration (v2024.12.1), press 'Reconfigure' on the Studer-Innotec integration page and add param RCC 5012. After that, press 'devices' and choose 'RCC'. The User Level is now visible as a diagnostics sensor in the integration.

**Comment by monstromatic** [comment]
The user level is EXPERT.

When I activate the switch in HA, everything happens normally but when I look at the RCC, the parameter is not modified and after the polling interval, the initial state (unmodified) is returned to HA.
To sum up, the switch in HA does not modify the studer system.

<img width="1412" alt="Capture d’écran 2024-12-08 à 15 35 08" src="https://github.com/user-attachments/assets/12009b06-a016-46bd-a2ba-679b7dbbc988">

**Comment by ankohanse** [comment]
It is correct that you will not see your change when you inspect your param via the RCC. This is explained in the ReadMe of the Studer-Innotec integration:

# Entity writes to device

When the value of a Studer param is changed via this integration (via a Number, Select or Switch entity), these are written via Xcom to the affected device. 
Changes are stored in the device's RAM memory, not in its flash memory as you can only write to flash a limited number of times over its lifetime.

However, reading back the value from the entity will always be from flash. As a result, the change to the entity value is not visible in the RCC or remote console. You can only tell from the behavior of the PV system that the Studer param was indeed changed.  

After a restart/reboot of the PV system the system will revert to the value from Flash. So you may want to periodically repeat the write of changed param values via an automation.

**Comment by ankohanse** [comment]
However, one other line in your response makes me wonder if there still is a bug in my code:
"and after the polling interval, the initial state (unmodified) is returned to HA"

So you turn the switch On (or Off), it displays in HA as On (or Off) and then after 30 seconds it suddenly reverts to display as Off (or On) again?

To make things appear more logical in the HA integration despite the weird RAM/Flash behavior of the Studer hardware, I cache/remember modified values in the integration to keep displaying them as modified. So a Switch turned On will modify the RAM memory state of the Studer Device into On. The device will behave accordingt to the RAM value. However, the Flash value will still return the Off value. I ignore that and keep displaying the On value for the switch in HA. This modified value is persisted in a file, so that the integration will keep remembering the change even after a restart of HA.

You can see this cache when you download the diagnostics for the integration (see above for steps). The following section should be in it (but for you for param 1127 instead of 1521):
```
        "cache": {
          "ModifiedParams": {
            "ts": "2024-08-29T20:43:23.895947",
            "studer_4001_xt1_1521": 0
          },
          "ModifiedParamsTs": "2024-12-09T11:13:25.602811"
        },
```
Could you please check the modified param is indeed stored in cache?

**Comment by monstromatic** [comment]
Your explanations (RAM / Flash) make sense, that's probably what's happening. I'd have to find a parameter to change that is visible in the behaviour of my system to check.

Concerning the integration cache system, there does seem to be a bug because the contents of the cache parameter are always empty in my successive tests.

    "cache": {},

**Comment by monstromatic** [comment]
Another strange behavior of the integration: I updated the version from 2024.11.4 to 2024.12.1 today but it still displays 2024.11.4.
I confirm the new version is use because I could import the param 5012 now and couldn't before...

**Comment by ankohanse** [comment]
The version number was my mistake, forgot to update it in the code before I published the new release.

OK, so somehow something is going wrong with the caching of modified param values on your system. I created a new release v2024.12.2 (now with version internally correct) that also will log warnings if unexpected behavior around the cache is detected.
Could you please give that a try?

Also, would it be possible for you to check if you have a file `/homeassistant/.storage/studer_xcom.coordinator` (note the dot in .storage) using ftp or ssh; it is not visible via the file editor inside HA. And place the contents in a comment here. Should look similar to what the 'cache' section of the diagnostics download looks like.

**Comment by monstromatic** [comment]
"cache": {
          "ModifiedParams": {
            "studer_4001_xt1_1127": 0,
            "studer_4001_xt1_1521": 0
          },
          "ModifiedParamsTs": "2024-12-09T09:50:59.369888"
        },

And good news, the switch now stay on (or off) in HA!

**Comment by monstromatic** [comment]
in coordinator: 

{
  "version": 1,
  "minor_version": 0,
  "key": "studer_xcom.coordinator",
  "data": {
    "4001": {
      "cache": {
        "ModifiedParams": {
          "studer_4001_xt1_1127": 1,
          "studer_4001_xt1_1521": 0
        },
        "ModifiedParamsTs": "2024-12-09T09:54:13.995180"
      }
    }
  }
}

**Comment by ankohanse** [comment]
Yes, those structures look as expected now.
This new version had mostly tracing changes in it, but simplified one part of cache handling too. That may just have done the trick to solve this.

Could you please keep an eye on whether the switch keeps its value after a HA restart?

**Comment by monstromatic** [comment]
Yes, the switch also keeps its value after restart.
Thank a lot for this integration and for solving this problem quickly!

**Comment by monstromatic** [comment]
There may be another point to correct:
When you click "reconfigure" the integration, the BMS parameters you added manually disappear. For example, I have to re-add parameter 7003 each time.

**Comment by ankohanse** [comment]
I will create a new Bug Report for the disappearing params wile doing a reconfigure. Hadn't noticed that behavior for params on other devices, so may be a bug specific to BMS
